services:
  minecraft:
    image: itzg/minecraft-server:java21
    container_name: minecraft-server
    network_mode: host
    environment:
      EULA: "TRUE"
      VERSION: "1.21.1"
      TYPE: "FABRIC"
      MEMORY: "4G"
      DIFFICULTY: "normal"
      OPS: "SythFlux"
    volumes:
      - ./minecraft-data:/data
    restart: unless-stopped
    stdin_open: true
    tty: true

  playit:
    image: ghcr.io/playit-cloud/playit-agent:0.17
    network_mode: host
    env_file:
      - .env
    restart: unless-stopped